### ISSUE TITLE
ModuleNotFoundError: No module named 'idlelib'

### ISSUE THREAD

**Issue by MuellerSeb** [mcuntz/ncvue#1]
Hey there,
thanks for this promising package!
Unfortunately, I ran into a problem using it out-of-the-box on Ubuntu 18.04.
When running `ncvue` from the command line, I got:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/ncvue", line 23, in <module>
    from ncvue import ncvue
  File "/usr/local/lib/python3.6/dist-packages/ncvue/__init__.py", line 30, in <module>
    from .ncvwidgets import Tooltip
  File "/usr/local/lib/python3.6/dist-packages/ncvue/ncvwidgets.py", line 46, in <module>
    from idlelib.tooltip import Hovertip
ModuleNotFoundError: No module named 'idlelib'
```

I could fix this by ([source](https://askubuntu.com/a/1307516)):
```bash
sudo apt install idle3
```

Maybe this could be a good hint for the install instructions.

Have a nice weekend!
Cheers, Sebastian

**Comment by mcuntz** [comment]
Thanks Sebastian.

I did not know that IDLE is not installed by default on Linux, contrary to macOS and Windows. I detail this in the docs now.

It also looks like that there was a major update on IDLE in Python 3.5 so ncvue actually needs Python 3.5 or later because of the tooltips. I hence also dropped the false statement of older Python support.

I would be happy for any other feedback while using ncvue. Also what additional features you or your colleagues might find useful.

Kind regards,
Matthias
