### ISSUE TITLE
Cannot open on Big Sur

### ISSUE THREAD

**Issue by jiho** [mcuntz/ncvue#2]
I have enabled the preference to run apps from the App Store and identified developers. I have selected "open anyway" when asked and this not asked anymore, so I suppose it was taken into account.

Yet the app does not run. The icon appears and then disappears and the system.log shows
```
Jul 21 22:05:45 charles com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.ncvue.5986205.5990769(501)> [39288]
Jul 21 22:05:45 charles com.apple.xpc.launchd[1] (application.ncvue.5986205.5990769[43634]): Service exited with abnormal code: 255
```

This code seems commonly related to SSH (as per a web search and [this StackExchange question](https://apple.stackexchange.com/questions/171465/sshd-service-exited-with-abnormal-code-255/329503), but I don't see the link with ncvue. Plus, I've enabled SSH access and ncvue still does not start.

I've tried installing through pip but keep hitting problems with dependencies.

**Comment by mcuntz** [comment]
Dear jiho,

sorry for the late reply. It was holiday season in France :-)

Do you have a Mac with an Intel chip or the (new) M1?

I just checked the latest version on Big Sur on Intel chip and that worked fine. It is rev 3.6 and can be found here: [ncvue-3.6](http://www.macu.de/extra/ncvue-3.6.dmg). You right-click (control-click) on the app the first time and choose 'Open' (and 'Open' again in the box).

However, this is not working on the new Apple Silicon (M1) chip because the code has to be signed with an Apple developer certificate. I got the machine pretty recently and I have not figured out yet how to sign the app without paying 99 EUR/year.

But the code itself also works on the M1 because it is written in (pure) Python. However, it was rather a pain to install the underlying libraries on the M1. I tried to write that down properly in the [installation instructions](https://mcuntz.github.io/ncvue/html/install.html#macos). You can see that there is even a patch to the Shapely library to get it working on the M1 (or rather with the new install path of homebrew on the M1). It would be great if you could try the instructions. In the optimal case, you can simply copy/paste the green boxes into a terminal :-)

I am happy about any feedback.

Kind regards,
Matthias

**Comment by mcuntz** [comment]
Hey @jiho

did you have a chance to try installing `ncvue` on the command line as given in the [installation instructions](https://mcuntz.github.io/ncvue/html/install.html#macos). You might not have seen my answer because I forgot to ping you.

Kind regards,
Matthias

**Comment by jiho** [comment]
No, sorry. I ended up using another solution because I was in a hurry and complex installation procedures were not appropriate in the context of teaching (that I was hoping to use ncvue for). I can revisit the issue if that is helpful.
