### ISSUE TITLE
MacOS darkmode not supported

### ISSUE THREAD

**Issue by StephanThober** [mcuntz/ncvue#4]
Hi Matthias,

thanks for putting this great tool together. I use MacOS dark-mode by default, but in ncvue, the button colors are not changed correctly, i.e., ncvue shows white symbols on white background, see screenshot attached. Did I set something not correctly or is this an issue?

Best,
Stephan

<img width="961" alt="Screenshot 2022-05-10 at 14 18 38" src="https://user-images.githubusercontent.com/19333234/167626527-9bd9931b-ebd7-4e7e-bb91-affb539fa523.png">

**Comment by mcuntz** [comment]
Thanks @StephanThober 

This is strange because this always worked for me on Mac (see below).

What macOS version, Python version and matplotlib version are you using:
```
uname -r
python --version
python -c "import matplotlib as mpl ; print(mpl.__version__)"

```
Note that I also install a new Tcl/Tk when setting up a new macOS. Search for "tcl" in [https://github.com/mcuntz/setup_mac](https://github.com/mcuntz/setup_mac).
Try to install version 8.6 if your macOS comes with 8.5:
`python -c "import tkinter as tk ; print(tk.TkVersion)"`
My best bet is actually that you use an old Tcl/Tk version.

Kind regards,
Matthias

![Screen Shot 2022-05-10 at 16 56 37](https://user-images.githubusercontent.com/13037588/167675193-37e66ae3-3a5b-4f63-9981-1c9ae92b1055.jpg)

**Comment by StephanThober** [comment]
Hi Matthias,

thanks for the fast reply. Here is the info from the command line:

```
uname -r
21.4.0
python --version
Python 3.10.4
python -c "import matplotlib as mpl ; print(mpl.__version__)"
3.5.2
python -c "import tkinter as tk ; print(tk.TkVersion)"
8.6
```
So this looks fine, doesn't it? I followed the conda install. There TCL seems to be not installed, only TK. I am not sure if this is an issue. If I try to install this package https://anaconda.org/intel/tcl , then conda runs into conflicts :(. Does the darkmode work for you in a conda environment?

Thanks,
Stephan

**Comment by mcuntz** [comment]
Hey @StephanThober ,

I simply don't know if there are different widgets of the Navigation bar for Light mode and for Dark mode.
Could you try the following please:
- Set your OS to Light Mode
- Start ncvue
- Set your OS to Dark Mode

Then ncvue changes to Dark Mode as well.

Another thing is how you actually install Python, not a virtual environment with conda, e.g.
I use Tcl/Tk from homebrew
`brew install tcl-tk`
And then I use it when installing Python itself
```
env PYTHON_CONFIGURE_OPTS="--with-tcltk-includes='-I${HOMEBREW_PREFIX}/opt/tcl-tk/include' \
    --with-tcltk-libs='-L${HOMEBREW_PREFIX}/opt/tcl-tk/lib -ltcl8.6 -ltk8.6' \
    --enable-framework" \
    CFLAGS="-I$(brew --prefix xz)/include" LDFLAGS="-L$(brew --prefix xz)/lib" \
    PKG_CONFIG_PATH="$(brew --prefix xz)/lib/pkgconfig" \
    pyenv install 3.9.9
```
Any virtual environement uses this tagged Python then.

I do not know how to do it with the anaconda command line installer. Of course, if you'd use pyenv to install anaconda or miniconda ... ;-)

**Comment by StephanThober** [comment]
Hi Matthias,

if I start ncvue in light mode and switch to dark mode, the issue persists.

I will try your way of installation and get back to you then. Thank you for your help!
